// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: adapterResponse.proto

package adapterResponse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdapterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries   []*SchemaEntry `protobuf:"bytes,1,rep,name=Entries,proto3" json:"Entries,omitempty"`
	Timestamp int64          `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *AdapterResponse) Reset() {
	*x = AdapterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapterResponse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterResponse) ProtoMessage() {}

func (x *AdapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapterResponse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterResponse.ProtoReflect.Descriptor instead.
func (*AdapterResponse) Descriptor() ([]byte, []int) {
	return file_adapterResponse_proto_rawDescGZIP(), []int{0}
}

func (x *AdapterResponse) GetEntries() []*SchemaEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AdapterResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SchemaEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Tag             string `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Namespace       string `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	NamespacePrefix string `protobuf:"bytes,4,opt,name=NamespacePrefix,proto3" json:"NamespacePrefix,omitempty"`
	Value           string `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *SchemaEntry) Reset() {
	*x = SchemaEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapterResponse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaEntry) ProtoMessage() {}

func (x *SchemaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_adapterResponse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaEntry.ProtoReflect.Descriptor instead.
func (*SchemaEntry) Descriptor() ([]byte, []int) {
	return file_adapterResponse_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaEntry) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SchemaEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SchemaEntry) GetNamespacePrefix() string {
	if x != nil {
		return x.NamespacePrefix
	}
	return ""
}

func (x *SchemaEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_adapterResponse_proto protoreflect.FileDescriptor

var file_adapterResponse_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x67, 0x0a, 0x0f, 0x41, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x45,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61,
	0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x45, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x91, 0x01, 0x0a, 0x0b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_adapterResponse_proto_rawDescOnce sync.Once
	file_adapterResponse_proto_rawDescData = file_adapterResponse_proto_rawDesc
)

func file_adapterResponse_proto_rawDescGZIP() []byte {
	file_adapterResponse_proto_rawDescOnce.Do(func() {
		file_adapterResponse_proto_rawDescData = protoimpl.X.CompressGZIP(file_adapterResponse_proto_rawDescData)
	})
	return file_adapterResponse_proto_rawDescData
}

var file_adapterResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_adapterResponse_proto_goTypes = []interface{}{
	(*AdapterResponse)(nil), // 0: adapterResponse.AdapterResponse
	(*SchemaEntry)(nil),     // 1: adapterResponse.SchemaEntry
}
var file_adapterResponse_proto_depIdxs = []int32{
	1, // 0: adapterResponse.AdapterResponse.Entries:type_name -> adapterResponse.SchemaEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_adapterResponse_proto_init() }
func file_adapterResponse_proto_init() {
	if File_adapterResponse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adapterResponse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdapterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adapterResponse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchemaEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adapterResponse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_adapterResponse_proto_goTypes,
		DependencyIndexes: file_adapterResponse_proto_depIdxs,
		MessageInfos:      file_adapterResponse_proto_msgTypes,
	}.Build()
	File_adapterResponse_proto = out.File
	file_adapterResponse_proto_rawDesc = nil
	file_adapterResponse_proto_goTypes = nil
	file_adapterResponse_proto_depIdxs = nil
}
